### ISSUE TITLE
Project boards

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney_vue#29]
### Could include:

- Ideas/backlogs board
- Current Projects board
- Completed Projects board

A possible additional feature would be voting on ideas/backlogs.

**Comment by thechintan123** [comment]
Hi @QjStout 
Can I take this enhancement if you are ok about it..?

**Comment by QjStout** [comment]
@thechintan123 we have no information on the requirements for it yet. That said, if you wanted to work on it anyway while we are having this lull in the project, that's cool with me. ¯\_(ツ)_/¯

There will be more work to do on this project soon though, I just haven't had the time to study the design documents yet.
