### ISSUE TITLE
SWAG SHAWP!

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney_vue#34]
I can't wait to get a Code.Sydney hoodie!

**Comment by engramar** [comment]
@QjStout This is pretty much my Capstone Project so I will take this one. Actually it is pretty much the code base from Vue Mastery, I just need to tweak it a little. =)

**Comment by engramar** [comment]
Sorry Qj. I remember you mentioned 'except enhancements'. I am not following instructions. =) Anyway, this can be for future inclusion if ever. Thanks.

**Comment by QjStout** [comment]
Haha no problem @engramar. We can keep it assigned to you for later and you can just work on it whenever you like.

**Comment by engramar** [comment]
Prototype done @QjStout. We can just think later how to integrate this to the new website. 

Link to App: https://master.d1bhgi2pi05bwx.amplifyapp.com/
API Swagger Documentation: https://merch.pythonanywhere.com/

**Comment by QjStout** [comment]
Excellent, I think that will work best to merge it in later when the first phase of the site is done.

Haven't had a chance to look at it on PC yet, but looking good on the phone man 👍.
