### ISSUE TITLE
Implement CI

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney_vue#52]
This is primarily for learning purposes. It's not strictly necessary for a project of this size.

**Comment by kimchirice** [comment]
reckon CI is  an option on Netlify if we chose that was the one to go with. if AWS Amplify,  I need to do some research with it, or we could implement it together. thanks mate

**Comment by QjStout** [comment]
Hey @kimchirice, I was planning on going with AWS Amplify, unless someone gives me a good reason to go with Netlify instead. Mostly just because I see a lot of job postings talking about AWS, so I want to start getting my toes wet there.

I'd like to be involved in this one, so we can do it together. I have to get some dependency issues done first, so I'll leave this unassigned for now and we can look at it again down the road.

**Comment by QjStout** [comment]
Actually, I'm not going with AWS. Turns out you can't set hard limits on AWS and a quick Google shows a tonne of people who ended up with 50k+ debts to AWS because of simple mistakes or being hacked. I've gotta get ready for work now but I'll look into Netlify when I can.

**Comment by engramar** [comment]
@QjStout I remember reading an article about surprise AWS billing. Apparently, the guy executed a very costly machine learning stuff (if I remember it correctly) and it cost the company millions I believe. I learned it the hard way. I experienced getting an unexpected bill of ~$60 just by keeping an EC2 instance up and running.  =) There are some ways to prevent surprise AWS billings and I think if you are not running very costly processes, it is relatively safe.

**Comment by engramar** [comment]
@kimchirice Netlify pricing is not bad https://www.netlify.com/pricing/. I think both Netlify and Amplify support CI/CD but sounds good if you can use this project to showcase CI/CD concept. It is a good playground for it.

**Comment by QjStout** [comment]
Assigning this to you if you still want it @kimchirice

**Comment by kimchirice** [comment]
for sure, I've been looking for a sound CI solution. will keep discussing with you @QjStout, @engramar and the team.

**Comment by engramar** [comment]
Oops Sorry @kimchirice , I thought it was just pinned from my side. My bad. I just repinned it. =)

**Comment by kimchirice** [comment]
hi @QjStout and @engramar,  sharing my thoughts here, hoping we could then refer back to it in the future. I need to understand your vision, of what kind of unit testing and/or integration testing we wanted to setup?? 

 my understanding to the CI on this project, we wanted to add automation test(s) to the current pipeline, summarized at below,

--> whenever PR is ready (reviewed and approved to merge) 
<br />--> built with a [_Deploy Preview_](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/) on Netlify(successfully) 
<br />--> automation test ( whatever we throw at it) passed 
<br />--> publish the new build

however if test failed, therefore we will NOT publish new build, but trigger a notification to the team, stating the "test not passed". 

further reading, checking it here, [_[Support Guide] Testing your Netlify builds_](https://community.netlify.com/t/support-guide-testing-your-netlify-builds/1456)

but I am more like getting lost of how to get this done... your thoughts??

**Comment by QjStout** [comment]
I like your suggestions.

I would love to see a singular place we could add our JavaScript unit tests. There isn't that much to test atm, but once we move onto other features after the homepage it would be really useful.

I think we're going to ignore UI testing. It's too time consuming and specialised a skillset for our team and this project.

When it comes to the implementation, I really have no idea man. I've never set something like this up. It is however an enhancement feature, so if you're finding that it's too much trouble we can shelve it.

**Comment by engramar** [comment]
Good morning @kimchirice and @QjStout , I am off from work today and Monday so catching up with all my GitHub notifications. You are pretty much on the next level thinking already @kimchirice 

Most of us here are still trying to enhance the application development side of our skills, particularly around Vue. I am glad you are looking at what I see is more on the DevOps side of things. Your steps seem logical and I like the idea of having a 'Deploy Preview'. 

My take is just start with the usual most basic CI practice within Netlify then we just improve on top of it. This also means Netlify might be our goto PaaS for all our future applications that we will build in Code.Sydney especially if we will have a well established CI process around it.

We are getting there, we have this GitHub collaboration working already. If you add you CI process, we will have a more standardized way of building stuff which can mean we will be ready to take on more complex projects in the future. Cheers!

**Comment by suryast** [comment]
You need to write some tests first :D

**Comment by engramar** [comment]
Good to see you here, @suryast =)

**Comment by kimchirice** [comment]
Do you gents have a preference of which test library to go with? 

personally I have been writing some test cases since last 2 or 3 week with [testing-library](https://testing-library.com/), well with React. Feeling pumped with _**render**_ and _**fireEvent**_, wanna test it with Vue. realized this morning after watching Vuemastery tutorial, that they were actually using [Vue test utils](https://vue-test-utils.vuejs.org/). any real-world experience, TBH, I dont want to go down with **wrapper** in vue-test-utils. @suryast @engramar @QjStout @promie @chenhe-henry

**Comment by QjStout** [comment]
I have no idea @kimchirice. I've never done testing for JavaScript and have no idea how it works. Do you have to use different testing frameworks dependent on what JS framework you're using? That seems like it would be a mess.

**Comment by promie** [comment]
@kimchirice if you're testing vue components its best to go with the vue-test-utils man. It's pretty much the same as testing React components. Why don't you want to go down with wrapper? Isn't it the same as shallowMount or mount in React?

**Comment by engramar** [comment]
Hello @kimchirice, Thanks again for joining the project meeting earlier. Actually, I just learned a test library last weekend but for Python. =) I guess the suggestion from Promie to use vue-test-utils makes sense if you will test Vue applications. I am guessing it is more fit-for-purpose in that regard. Cheers!

**Comment by suryast** [comment]
There is mostly just one which is Jest. Everything else is just framework-specific wrappers for Jest usually – go for it 👍
