### ISSUE TITLE
Interim manual onboarding of members

### ISSUE THREAD

**Issue by engramar** [codesydney/codesydney_vue#76]
As agreed with @QjStout, while we are waiting for the proper provision of a self-service portal, we will start doing an interim manual onboarding of members.

**Comment by QjStout** [comment]
Is this complete @engramar? If not, under what conditions would you consider it complete?

**Comment by engramar** [comment]
Hello @QjStout, I see this as an ongoing issue. I think we can only close this once the self-service portal is available which I think is in Phase 2. For the time being, I am happy to onboard people manually in the database.
