### ISSUE TITLE
Make the height of Banner + Headline = 100% screen height.

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney_vue#80]
Everything from the start of the page to the "Book a meeting with me" button should be exactly the height of the screen.
This should be the case on both mobile and desktop.

*** Reference:
![screenheightissue](https://user-images.githubusercontent.com/19155822/95286070-0370fc00-08ae-11eb-8da4-bcbef137b073.PNG)

**Comment by NimaSakha** [comment]
Hi, can I please work on this issue?

**Comment by engramar** [comment]
Hello @NimaSakha, I think this is the old Vue version of the website. This project is not active anymore. Look at this new project instead https://github.com/codesydney/codesydneywebsite/issues. Thanks.
